
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.shuai.springbootproject.entity
spring:
  datasource:
    username: shuai
    password: shuai
    url: jdbc:oracle:thin:@localhost:1521:ORCL
    driver-class-name: oracle.jdbc.driver.OracleDriver
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    password: 111111
    redis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
      timeout: 1000
